# Generated by Django 5.0.2 on 2024-02-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
